export const GET_MESSAGE = "ui/GET_MESSAGE";
export const SET_SUCCESS_MESSAGE = "ui/SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = "ui/SET_ERROR_MESSAGE";
export const CLEAR_MESSAGE = "ui/CLEAR_MESSAGE";
export const GET_UPDATE_INTERVAL = "ui/GET_UPDATE_INTERVAL";
export const SET_UPDATE_INTERVAL = "ui/SET_UPDATE_INTERVAL";
